development:
  adapter: postgresql
  encoding: unicode
  database: gururs_development
  pool: 5
  username: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gururs_test
  pool: 5
  username: postgres
  min_messages: WARNING
  host: localhost
